### ISSUE TITLE
自動更新版でnimlodLAFがうまく動作しない。

### ISSUE THREAD

**Issue by yusukemihara** [montsuqi/monsiaj#88]
nimlodへの切り替えで以下のエラーがでて、テキストフィールドやコンボボックスが表示されない。
バイナリ版では(似たようなエラーがでるものの)動作するので自動更新版で外部jarから起動する部分との関連でエラーになる模様。

自動更新版ではnimlodを無効化するなどが必要かも知れない。

```
04/10 16:45:06 [INFO ] ---- Loader start
04/10 16:45:06 [INFO ] cacheVersion : 2.0.14
04/10 16:45:06 [INFO ] serverVersion: 2.0.14
04/10 16:45:06 [INFO ] use cache
04/10 16:45:07 [INFO ] ---- start monsiaj
04/10 16:45:07 [INFO ] version : 2.0.14
04/10 16:45:07 [INFO ] java : 10.0.2
04/10 16:45:07 [INFO ] os : Linux-4.15.0-45-generic-amd64
04/10 16:45:07 [WARN ] invalid printer config! skip this. []
04/10 16:45:08 [INFO ] ---- Loader end
java.lang.Error: no ComponentUI class for: javax.swing.JComboBox[,55,7,590x27,layout=javax.swing.plaf.metal.MetalComboBoxUI$MetalComboBoxLayoutManager,alignmentX=0.0,alignmentY=0.0,border=,flags=328,maximumSize=,minimumSize=,preferredSize=,isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=trial]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JComboBox.updateUI(JComboBox.java:277)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
	at org.montsuqi.monsiaj.client.ConfigPanel.lambda$changeLookAndFeel$0(ConfigPanel.java:234)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.Error: no ComponentUI class for: javax.swing.JTabbedPane[,5,36,642x366,layout=javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneScrollLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=352,maximumSize=,minimumSize=,preferredSize=,haveRegistered=false,tabPlacement=TOP]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JTabbedPane.updateUI(JTabbedPane.java:245)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
	at org.montsuqi.monsiaj.client.ConfigPanel.lambda$changeLookAndFeel$0(ConfigPanel.java:234)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.Error: no ComponentUI class for: javax.swing.JTextField[,205,13,427x22,layout=javax.swing.plaf.basic.BasicTextUI$UpdateHandler,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@bc50fee,flags=296,maximumSize=,minimumSize=,preferredSize=,caretColor=sun.swing.PrintColorUIResource[r=51,g=51,b=51],disabledTextColor=javax.swing.plaf.ColorUIResource[r=184,g=207,b=229],editable=true,margin=javax.swing.plaf.InsetsUIResource[top=0,left=0,bottom=0,right=0],selectedTextColor=sun.swing.PrintColorUIResource[r=51,g=51,b=51],selectionColor=javax.swing.plaf.ColorUIResource[r=184,g=207,b=229],columns=0,columnWidth=0,command=,horizontalAlignment=LEFT]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
略
```

**Comment by yusukemihara** [comment]
PR #92
